<#
-----------------------------------------------------------------------
Name: Oregon Death Record Raw File Cleaner
Author: Anthony Dunaway
Date: 05/21/2018
Updated: 06/08/2018
Description:
Cleans up text files generated by the ODI record extractor script.
-----------------------------------------------------------------------
#>

$location = Get-Location
."$location\User_Input.ps1"

Write-Host "Master File Cleaner"
$run_middle = Get-UserInput -Question 'Do you want to process middle names?        '
$run_first = Get-UserInput -Question 'Do you want to process first names?         '
$file_path = "$location\master_files\"
$last = "master_last.txt"
$first = "master_first.txt"
$middle = "master_middle.txt"
$date = "master_date.txt"
#Original find replace code found here: https://datainthecity.net/2013/04/15/replacing-multiple-strings-in-text-files-with-powershell/ 
#------------------------------------------------------------------------------------------------------------------------
# Clean up middle name master file
#------------------------------------------------------------------------------------------------------------------------	
if($run_middle -eq 1){
	$corrections = "$location\replacements.csv"
	$file_to_correct = "$file_path$middle"
	$ReplacementList = Import-Csv $corrections
	Get-ChildItem $file_to_correct | Out-Null
	$Content = Get-Content $file_to_correct;
	foreach ($ReplacementItem in $ReplacementList){
		$Content = $Content.Replace($ReplacementItem.OldValue, $ReplacementItem.NewValue)
	}
	Set-Content $file_to_correct -Value $Content
	(gc $file_path$middle) | ? {$_.trim() -ne "" } | set-content $file_path$middle
}
#------------------------------------------------------------------------------------------------------------------------
# Remove  from each of the files as well as commas and empty lines
#------------------------------------------------------------------------------------------------------------------------	
if(($run_first -eq 1) -and ($run_middle -eq 1)){
	$files = ("$file_path$last", "$file_path$first", "$file_path$middle", "$file_path$date")	
}
elseif(($run_first -eq 1) -and ($run_middle -eq 0)){
	$files = ("$file_path$last", "$file_path$first", "$file_path$date")
}
elseif(($run_first -eq 0) -and ($run_middle -eq 1)){
	$files = ("$file_path$last", "$file_path$middle", "$file_path$date")
}
else{
	$files = ("$file_path$last", "$file_path$date")
}

foreach($txt in $files){
	$content = [System.IO.File]::ReadAllText("$txt").Replace(''," ") 
	$content = [System.IO.File]::ReadAllText("$txt").Replace(','," ") 
	[System.IO.File]::WriteAllText("$txt", $content)
	(gc $txt) | ? {$_.trim() -ne "" } | set-content $txt
}